name: CI

on:
  - push
  - pull_request

env:
  CI: true

jobs:
  Test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Pulsar
        uses: pulsar-edit/action-pulsar-dependency@v3.4
      - name: Install package dependencies
        run: pulsar -p install
      - name: Run tests (Linux, headless)
        if: runner.os == 'Linux'
        run: xvfb-run --auto-servernum pulsar --test test
      - name: Run tests (macOS / Windows)
        if: runner.os != 'Linux'
        run: pulsar --test test
